/*
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * API version: 2.0.831
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package bombbomb

import (
	"time"
)

// The CurriculumUserProgress class
type CurriculumUserProgress struct {

	// Id
	Id string `json:"id,omitempty"`

	// User Id
	UserId string `json:"userId,omitempty"`

	// Curriculum Item Id
	CurriculumItemId string `json:"curriculumItemId,omitempty"`

	// Curriculum Id
	CurriculumId string `json:"curriculumId,omitempty"`

	// When the final email is scheduled to be sent
	CompletedDate time.Time `json:"completedDate,omitempty"`
}
