/*
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * API version: 2.0.831
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package bombbomb

import (
	"time"
)

// The HostedDoc class
type HostedDoc struct {

	// The doc's id.
	Id string `json:"id,omitempty"`

	// The doc's owner.
	UserId string `json:"userId,omitempty"`

	// docs file name.
	FileName string `json:"fileName,omitempty"`

	// The doc's short url.
	ShortUrl string `json:"shortUrl,omitempty"`

	// The doc's long url.
	LongUrl string `json:"longUrl,omitempty"`

	// The doc's upload date.
	UploadDate time.Time `json:"uploadDate,omitempty"`
}
