/*
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * API version: 2.0.831
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package bombbomb

// Reports on the aggregate performance of a Jericho send
type JerichoPerformance struct {

	// The jericho id
	JerichoId int32 `json:"jerichoId,omitempty"`

	// The number of emails sent
	Sent int32 `json:"sent,omitempty"`

	// The unique number of people that viewed the email
	UniqueViews int32 `json:"uniqueViews,omitempty"`

	// The unique number of people that visited the landing page
	UniqueLandingPageViews int32 `json:"uniqueLandingPageViews,omitempty"`

	// The total number of people that visisted the landing page
	LandingPageViews int32 `json:"landingPageViews,omitempty"`

	// The number of emails delivered, likely less than sent due to bounces, and other common delivery issues
	Delivered int32 `json:"delivered,omitempty"`

	// The number of emails that bounced as undeliverable
	Bounce int32 `json:"bounce,omitempty"`

	// The total number of times the emails were viewed
	Open int32 `json:"open,omitempty"`

	// The total number of times links in the emails were clicked
	Click int32 `json:"click,omitempty"`

	// The total number of times videos in the emails were played
	VideoPlay int32 `json:"videoPlay,omitempty"`

	// The number of recipients that marked the message as abusive
	AbuseComplaints int32 `json:"abuseComplaints,omitempty"`

	// The total number of contacts submitted to be sent, may be more than was sent to
	Contacts int32 `json:"contacts,omitempty"`

	// The total number of prompts sent to members of the client group
	PromptsSent int32 `json:"promptsSent,omitempty"`

	// The total number of prompts sent that included a personal recording
	PromptsWithRecordings int32 `json:"promptsWithRecordings,omitempty"`

	// The total number of members that chose not to send a prompt
	PromptsOptedOut int32 `json:"promptsOptedOut,omitempty"`
}
