/*
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * API version: 2.0.831
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package bombbomb

type OAuthClient struct {

	// The id of the OAuth Client
	Identifier string `json:"identifier,omitempty"`

	// The user-facing name of the client. Eg. MyCrm
	Name string `json:"name,omitempty"`

	// The secret supplied to the OAuth Application
	ClientSecret string `json:"clientSecret,omitempty"`

	// The grants allowed
	GrantsAllowed string `json:"grantsAllowed,omitempty"`

	// The user who controls the OAuth App
	OwningUserId string `json:"owningUserId,omitempty"`

	// Where OAuth authorization sessions are returned to
	RedirectUri string `json:"redirectUri,omitempty"`
}
