/* 
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.25797
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package bombbomb

import (
	"time"
)

// The Prompt\\Bot class
type PromptBot struct {

	// The identifier of the prompt bot. Read Only.
	Id string `json:"id,omitempty"`

	// The prompt bot's owner. Read Only.
	UserId string `json:"userId,omitempty"`

	// The default email being sent to contacts in the prompt bot list.
	EmailId string `json:"emailId,omitempty"`

	// The list to attach the Prompt Bot to.
	ListId string `json:"listId,omitempty"`

	// The name of the bot.
	Name string `json:"name,omitempty"`

	// The custom contact field value column used for this bot.
	ContactFieldValueColumn string `json:"contactFieldValueColumn,omitempty"`

	// The status of the prompt bot. Read Only.
	Status int32 `json:"status,omitempty"`

	// when the bot started
	StartDate time.Time `json:"startDate,omitempty"`

	// when the bot should finish
	EndDate time.Time `json:"endDate,omitempty"`

	// The type of bot.
	BotTypeId string `json:"botTypeId,omitempty"`

	// The template id used to generate the default email.
	TemplateId string `json:"templateId,omitempty"`

	// The video that was added to the prompt.
	VideoId string `json:"videoId,omitempty"`

	// The content to use in the email.
	Content string `json:"content,omitempty"`

	// The subject of the default email.
	Subject string `json:"subject,omitempty"`

	// Set when generated as a default by a bot.
	GeneratedBy string `json:"generatedBy,omitempty"`
}
