/* 
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package bombbomb

import (
	"time"
)

// The Prompt\\SocialPrompt class
type PromptSocialPrompt struct {

	// The identifier of the prompt. Read Only.
	Id string `json:"id,omitempty"`

	// The prompt's owner. Read Only.
	UserId string `json:"userId,omitempty"`

	// If sent in a jericho context, this will have the jericho id
	JerichoId string `json:"jerichoId,omitempty"`

	// The prompt's subject line
	PromptSubject string `json:"promptSubject,omitempty"`

	// The suggested script of the prompt.
	PromptHtml string `json:"promptHtml,omitempty"`

	// When the final email is scheduled to be sent
	ScheduledSendDate time.Time `json:"scheduledSendDate,omitempty"`

	// The client group campaign that created the prompt.
	ClientGroupId string `json:"clientGroupId,omitempty"`

	// The URL of a thumbnail image for this prompt
	ThumbnailUrl string `json:"thumbnailUrl,omitempty"`

	// The status of the prompt: created = 0, sent = 10, recorded = 20, job_created = 30, timed_out = 40, declined = 50 Read Only
	Status int32 `json:"status,omitempty"`

	// When the email was first sent out
	CreatedDate time.Time `json:"createdDate,omitempty"`

	// When the user was last notified about a prompt email waiting for a video
	LastNotified time.Time `json:"lastNotified,omitempty"`

	// The sendMechanism property
	SendMechanism time.Time `json:"sendMechanism,omitempty"`

	// The types of mechanisms this prompt can send.
	SendTypes []string `json:"sendTypes,omitempty"`
}
