/*
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * API version: 2.0.831
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package bombbomb

import (
	"time"
)

// The Prompt\\SocialPrompt class
type PromptSocialPrompt struct {

	// The identifier of the prompt. Read Only.
	Id string `json:"id,omitempty"`

	// The prompt's owner. Read Only.
	UserId string `json:"userId,omitempty"`

	// If sent in a jericho context, this will have the jericho id
	JerichoId string `json:"jerichoId,omitempty"`

	// The prompt's subject line
	PromptSubject string `json:"promptSubject,omitempty"`

	// The suggested script of the prompt.
	PromptHtml string `json:"promptHtml,omitempty"`

	// When the final email is scheduled to be sent
	ScheduledSendDate time.Time `json:"scheduledSendDate,omitempty"`

	// The client group campaign that created the prompt.
	ClientGroupId string `json:"clientGroupId,omitempty"`

	// The URL of a thumbnail image for this prompt
	ThumbnailUrl string `json:"thumbnailUrl,omitempty"`

	// The status of the prompt: created = 0, sent = 10, recorded = 20, job_created = 30, timed_out = 40, declined = 50 Read Only
	Status int32 `json:"status,omitempty"`

	// When the email was first sent out
	CreatedDate time.Time `json:"createdDate,omitempty"`

	// When the user was last notified about a prompt email waiting for a video
	LastNotified time.Time `json:"lastNotified,omitempty"`

	// The sendMechanism property
	SendMechanism time.Time `json:"sendMechanism,omitempty"`

	// The types of mechanisms this prompt can send.
	SendTypes []string `json:"sendTypes,omitempty"`
}
