/*
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * API version: 2.0.831
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package bombbomb

// The PromptMonthlyPerformance class
type PromptMonthlyPerformance struct {

	// The startDate property
	StartDate string `json:"startDate,omitempty"`

	// The endDate property
	EndDate string `json:"endDate,omitempty"`

	// The userBatchListsIdHelper property
	UserBatchListsIdHelper string `json:"userBatchListsIdHelper,omitempty"`

	// The promptIdHelper property
	PromptIdHelper string `json:"promptIdHelper,omitempty"`
}
