/*
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * API version: 2.0.831
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package bombbomb

import (
	"time"
)

// The SignUploadRequest class
type SignUploadRequest struct {

	// when the upload will expire.
	Expiration time.Time `json:"expiration,omitempty"`

	// Key/Value object of request conditions.
	Conditions *interface{} `json:"conditions,omitempty"`
}
