/*
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * API version: 2.0.831
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package bombbomb

// The TeamPublicRepresentation class
type TeamPublicRepresentation struct {

	// The id of the team
	Id string `json:"id,omitempty"`

	// The name of the team
	Name string `json:"name,omitempty"`

	// The date the team was created
	CreatedDate string `json:"createdDate,omitempty"`
}
