---
swagger: "2.0"
info:
  description: "We make it easy to build relationships using simple videos."
  version: "2.0.831"
  title: "BombBomb"
host: "api.bombbomb.com"
basePath: "/v2"
tags:
- name: "EMAILS"
  description: "Emails"
- name: "CONTACTS"
  description: "Contacts"
- name: "LISTS"
  description: "Lists"
- name: "VIDEOS"
  description: "Videos"
- name: "UTILITIES"
  description: "Utilities"
- name: "WEBHOOKS"
  description: "Webhooks"
- name: "AUTOMATIONS"
  description: "Automations"
- name: "CURRICULUM"
  description: "Curriculum"
- name: "PROMPTS"
  description: "Prompts"
- name: "ORDERS"
  description: "Orders"
- name: "SOCIALS"
  description: "Socials"
- name: "TEAMS"
  description: "Teams"
- name: "ACCOUNTS"
  description: "Accounts"
- name: "INTEGRATIONS"
  description: "Integrations"
- name: "FILES"
  description: "Files"
- name: "FORMS"
  description: "Forms"
- name: "USERS"
  description: "Users"
schemes:
- "https"
paths:
  /account/profile/:
    post:
      tags:
      - "Accounts"
      summary: "Add profile information."
      description: "Add profile information to this users account"
      operationId: "UpdateProfileData"
      security:
      - BBOAuth2:
        - "account:manage"
  /accounts:
    get:
      tags:
      - "Accounts"
      summary: "Get account details."
      description: "Get the details of the user's account."
      operationId: "AccountDetails"
      security:
      - BBOAuth2:
        - "account:read"
    post:
      tags:
      - "Accounts"
      summary: "Create Account"
      description: "Creates a new BombBomb account. This method is currently only\
        \ available to paid seat admins."
      operationId: "CreateAccount"
      security:
      - BBOAuth2:
        - "account:manage"
  /accounts/apikey:
    put:
      tags:
      - "Accounts"
      summary: "Reset API key"
      description: "Resets the current user's API key and returns the new key"
      operationId: "ResetApiKey"
      security:
      - BBOAuth2:
        - "account:manage"
  /accounts/purchaseable:
    get:
      tags:
      - "Accounts"
      summary: "Check if subscription purchase allowed."
      description: "Check whether the user can purchase a subscription."
      operationId: "SubscriptionPurchaseAllowed"
      security:
      - BBOAuth2:
        - "account:read"
  /accounts/stats:
    get:
      tags:
      - "Accounts"
      summary: "Get Client Statistics"
      description: "Gets general statics for a Client"
      operationId: "GetClientStatistics"
      security:
      - BBOAuth2:
        - "account:read"
  /accounts/{clientId}/country:
    get:
      tags:
      - "Accounts"
      summary: "Gets user country"
      description: "Gets the users country"
      operationId: "GetUserCountry"
      security:
      - BBOAuth2:
        - "account:read"
  /automation/{dripId}/dripdrop/{dripDropId}/stats:
    get:
      tags:
      - "Automations"
      summary: "Get Automation Email Stats"
      description: "Get Automation Email Stats"
      operationId: "GetDripDropStats"
      security:
      - BBOAuth2:
        - "automation:read"
  /automation/{id}/scheduling/status:
    get:
      tags:
      - "Automations"
      summary: "Get the number of pending scheduling calculations"
      description: "Get the number of pending scheduling calculations"
      operationId: "GetSchedulingStatus"
      security:
      - BBOAuth2:
        - "automation:read"
  /automation/{id}/stats:
    get:
      tags:
      - "Automations"
      summary: "Get Automation Stats"
      description: "Get Automation Stats"
      operationId: "GetDripStats"
      security:
      - BBOAuth2:
        - "automation:read"
  /campaign/{campaignId}/content/alternate:
    get:
      tags:
      - "Prompts"
      summary: "List alternate campaign content"
      description: "Returns a list of alternate campaign content by campaign id"
      operationId: "GetAlternateCampaignContent"
      security:
      - BBOAuth2:
        - "email:read"
  /clients/contact/information:
    get:
      tags:
      - "Users"
      summary: "Get client contact information."
      description: "Get the client contact information of the user's account."
      operationId: "GetClientContactInformation"
      security:
      - BBOAuth2:
        - "account:read"
  /contact/{id}:
    get:
      tags:
      - "Contacts"
      summary: "Get Contact Details"
      description: "Get the contact details"
      operationId: "GetContactById"
      security:
      - BBOAuth2:
        - "contact:read"
  /contacts/:
    post:
      tags:
      - "Contacts"
      summary: "Add a contact."
      description: "Add a contact to the users list."
      operationId: "AddNewContact"
      security:
      - BBOAuth2:
        - "contact:manage"
  /contacts/custom_fields/:
    get:
      tags:
      - "Contacts"
      summary: "Get custom fields."
      description: "Get the current users custom fields."
      operationId: "GetCustomFields"
      security:
      - BBOAuth2:
        - "contact:manage"
    post:
      tags:
      - "Contacts"
      summary: "Add custom fields."
      description: "Add a new custom field."
      operationId: "AddNewCustomField"
      security:
      - BBOAuth2:
        - "contact:manage"
  /contacts/delete:
    put:
      tags:
      - "Contacts"
      summary: "Delete Contacts"
      description: "Delete all contacts within a list, or provide a comma separated\
        \ list of contactIds to delete."
      operationId: "DeleteContacts"
      security:
      - BBOAuth2:
        - "contact:manage"
  /contacts/import_csv:
    post:
      tags:
      - "Contacts"
      summary: "Add contacts from a CSV file."
      description: "Add multiple contacts through the upload importer from a CSV file."
      operationId: "AddContactsCSV"
      security:
      - BBOAuth2:
        - "contact:manage"
  /contacts/paste:
    post:
      tags:
      - "Contacts"
      summary: "Add pasted contacts."
      description: "Add the pasted contacts to the users list."
      operationId: "AddPastedContacts"
      security:
      - BBOAuth2:
        - "contact:manage"
  /csv-to-object:
    post:
      tags:
      - "Contacts"
      summary: "Format CSV."
      description: "Format a CSV file to an object."
      operationId: "CSVToObject"
      security:
      - BBOAuth2:
        - "contact:manage"
  /curricula/:
    get:
      tags:
      - "Curriculum"
      summary: "Get Curricula"
      description: "Get Curricula, optionally with progress included."
      operationId: "GetCurricula"
      security:
      - BBOAuth2:
        - "curriculum:read"
  /curriculum/getForUserWithProgress:
    get:
      tags:
      - "Curriculum"
      summary: "Get Detailed For User"
      description: "Get all curricula for user including progress for each curriculum."
      operationId: "GetUserCurriculumWithProgress"
      security:
      - BBOAuth2:
        - "curriculum:read"
  /emails/livefire:
    get:
      tags:
      - "Emails"
      summary: "Get livefire feed data"
      description: "Get the user data for the live fire feed emails"
      operationId: "GetLiveFireData"
      security:
      - BBOAuth2:
        - "email:read"
  /emails/print:
    post:
      tags:
      - "Emails"
      summary: "Create an Email with Printing Press"
      description: "Prints an email using the template id and content to the users\
        \ account.If a video id is included, it will replace any video placeholders\
        \ with that video."
      operationId: "CreatePrintingPressEmail"
      security:
      - BBOAuth2:
        - "email:manage"
  /emails/quicksend:
    get:
      tags:
      - "Emails"
      summary: "Get quicksend data"
      description: "Get the user data for quicksender, including templates and lists."
      operationId: "GetVideoQuickSenderData"
      security:
      - BBOAuth2:
        - "email:manage"
    post:
      tags:
      - "Emails"
      summary: "Send a quicksend email"
      description: "Send a quicksend video email to the list or users provided."
      operationId: "VideoQuickSender"
      security:
      - BBOAuth2:
        - "email:manage"
  /emails/quicksend/settings:
    post:
      tags:
      - "Emails"
      summary: "Save quicksender settings"
      description: "Save the quicksender notification and default template settings"
      operationId: "SaveQuickSenderSettings"
      security:
      - BBOAuth2:
        - "email:manage"
  /emails/quicksend/templates:
    get:
      tags:
      - "Emails"
      summary: "Get all quicksend templates"
      description: "Get all quicksend templates accessible to the user."
      operationId: "GetQuickSendTemplates"
      security:
      - BBOAuth2:
        - "email:read"
  /emails/templates:
    get:
      tags:
      - "Emails"
      summary: "Get all user templates"
      description: "Get all templates accessible to the current user"
      operationId: "GetAllTemplatesForCurrentUser"
      security:
      - BBOAuth2:
        - "email:read"
  /emails/templates/{templateId}/html:
    get:
      tags:
      - "Emails"
      summary: "Get the HTML for a given template"
      description: "Get the HTML for a given template, with or without rendered variables"
      operationId: "GetTemplateHtmlForTemplateId"
      security:
      - BBOAuth2:
        - "email:read"
  /emails/{emailId}/tracking:
    get:
      tags:
      - "Emails"
      summary: "Get Email Tracking"
      description: "Get Tracking data for all sends of an Email"
      operationId: "GetEmailTracking"
      security:
      - BBOAuth2:
        - "email:read"
  /emails/{emailId}/tracking/hourly:
    get:
      tags:
      - "Emails"
      summary: "Get Hourly Email Tracking"
      description: "Get Tracking data for an Email,\n            broken down by the\
        \ hour and filterable by an Interaction type"
      operationId: "GetHourlyEmailTracking"
      security:
      - BBOAuth2:
        - "email:read"
  /emails/{emailId}/tracking/interactions:
    get:
      tags:
      - "Emails"
      summary: "Get Email Tracking Interactions"
      description: "Get Contact detail interactions for an Email"
      operationId: "GetEmailTrackingInteractions"
      security:
      - BBOAuth2:
        - "email:read"
  /files:
    get:
      tags:
      - "Files"
      summary: "List all files"
      description: "List all uploaded user files"
      operationId: "DocHostList"
      security:
      - BBOAuth2:
        - "file:read"
    post:
      tags:
      - "Files"
      summary: "Upload a file"
      description: "Upload a new file"
      operationId: "DocHostUploadV2"
      security:
      - BBOAuth2:
        - "file:read"
  /files/images/paged:
    get:
      tags:
      - "Files"
      summary: "Get paged hosted images"
      description: "Get a specific page of uploaded images available to the user."
      operationId: "GetHostedImagesPaged"
      security:
      - BBOAuth2:
        - "file:read"
  /files/{docId}:
    get:
      tags:
      - "Files"
      summary: "Get file"
      description: "Get a single file by id"
      operationId: "DocHostGet"
      security:
      - BBOAuth2:
        - "file:read"
    delete:
      tags:
      - "Files"
      summary: "Delete file"
      description: "Deletes a users file"
      operationId: "DocHostDelete"
      security:
      - BBOAuth2:
        - "file:manage"
  /forms/{id}/tracking/export:
    get:
      tags:
      - "Forms"
      summary: "Get csv"
      description: "Get form tracking as csv"
      operationId: "GetFormTrackingAsCsv"
      security:
      - BBOAuth2:
        - "form:read"
  /integrations:
    post:
      tags:
      - "Integrations"
      summary: "Activate an integration for a user."
      description: "Provide the correct parameters to enable an integration. Required\
        \ Parameters vary based on the desired \n        integration. Integrations\
        \ requiring OAuth will provide the OAuth link that the user must be presented."
      operationId: "ConnectIntegration"
      security:
      - BBOAuth2:
        - "automation:manage"
    delete:
      tags:
      - "Integrations"
      summary: "Remove an integration for a user."
      description: "Remove an integration by providing the integration id or integration\
        \ code. Only provide one of the\n            parameters."
      operationId: "DeleteIntegration"
      security:
      - BBOAuth2:
        - "automation:manage"
  /integrations/health/{code}:
    get:
      tags:
      - "Integrations"
      summary: "Get health for a given integration"
      description: "Get health for an integration."
      operationId: "GetIntegrationHealth"
      security:
      - BBOAuth2:
        - "all:manage"
  /integrations/pageComponents:
    get:
      tags:
      - "Integrations"
      summary: "Get page components for a given integration"
      description: "Get all page components for an integration."
      operationId: "GetIntegrationPageComponents"
      security:
      - BBOAuth2:
        - "all:manage"
  /integrations/sync:
    get:
      tags:
      - "Integrations"
      summary: "Synchronize your integration list or lists."
      description: "Synchronize your integration contact list with the service you\
        \ are integrated with. If no integration code is provided, all integrations\
        \ will be synchronized."
      operationId: "SyncUsersIntegratedLists"
      security:
      - BBOAuth2:
        - "automation:manage"
  /lists/:
    get:
      tags:
      - "Lists"
      summary: "Get all Lists"
      description: "Get all the lists for a specific user."
      operationId: "GetAllLists"
      security:
      - BBOAuth2:
        - "list:manage"
    post:
      tags:
      - "Lists"
      summary: "Add list."
      description: "Add a list to the users account."
      operationId: "AddNewList"
      security:
      - BBOAuth2:
        - "list:manage"
  /lists/{listId}/clear:
    put:
      tags:
      - "Lists"
      summary: "Clear Contacts from List"
      description: "Clears all contacts from a list."
      operationId: "ClearList"
      security:
      - BBOAuth2:
        - "contact:manage"
  /lists/{listId}/copy:
    post:
      tags:
      - "Lists"
      summary: "Copy All Contacts from a List"
      description: "Copy all contacts from a list."
      operationId: "CopyListContacts"
      security:
      - BBOAuth2:
        - "contact:manage"
  /lists/{listId}/suppress:
    put:
      tags:
      - "Lists"
      summary: "Suppress All Contacts from List"
      description: "Suppresses all contacts in a list."
      operationId: "SuppressAllInList"
      security:
      - BBOAuth2:
        - "contact:manage"
  /oauthclient:
    get:
      tags:
      - "Utilities"
      summary: "Lists OAuth Clients"
      description: "Enumerates OAuth Clients managed by the user"
      operationId: "GetOAuthClients"
      security:
      - BBOAuth2:
        - "settings:manage"
    post:
      tags:
      - "Utilities"
      summary: "Create an OAuth Client"
      description: "Creates an OAuth Client managed by the user"
      operationId: "CreateOAuthClient"
      security:
      - BBOAuth2:
        - "settings:manage"
  /oauthclient/{id}:
    delete:
      tags:
      - "Utilities"
      summary: "Delete an OAuth Client"
      description: "Deletes an OAuth Client managed by the user"
      operationId: "DeleteOAuthClient"
      security:
      - BBOAuth2:
        - "settings:manage"
  /orders/templates/images:
    delete:
      tags:
      - "Orders"
      summary: "Deletes image from user s3 store"
      description: "Deletes image from user s3 store"
      operationId: "TemplateAssetDelete"
      security:
      - BBOAuth2:
        - "order:manage"
  /prompt:
    post:
      tags:
      - "Prompts"
      summary: "Prompts user to send a video"
      description: "Sends the account holder an email prompting them to add a video\
        \ to a scheduled outgoing message. Recipients, content and timing is all preset\
        \ for the user."
      operationId: "CreateVideoEmailPrompt"
      security:
      - BBOAuth2:
        - "email:manage"
  /prompt/:
    get:
      tags:
      - "Prompts"
      summary: "List prompts"
      description: "Returns a list of all prompts."
      operationId: "GetVideoEmailPrompts"
      security:
      - BBOAuth2:
        - "email:read"
  /prompt/pending:
    get:
      tags:
      - "Prompts"
      summary: "List pending prompts"
      description: "Returns a list of prompts that have not been sent yet, and can\
        \ still be customized."
      operationId: "GetPendingVideoEmailPrompts"
      security:
      - BBOAuth2:
        - "email:read"
  /prompt/{id}:
    get:
      tags:
      - "Prompts"
      summary: "Gets a prompt"
      description: "Gets a prompt"
      operationId: "GetVideoEmailPrompt"
      security:
      - BBOAuth2:
        - "email:read"
  /prompt/{id}/response:
    post:
      tags:
      - "Prompts"
      summary: "Respond to a prompt"
      description: "Respond to a prompt by either adding a video, sending without\
        \ a video or cancelling the prompt."
      operationId: "RespondToVideoEmailPrompt"
      security: []
  /prompt/{id}/sendit:
    post:
      tags:
      - "Prompts"
      summary: ""
      description: "Ignore send date and send the prompt now."
      operationId: "SendPromptImmediately"
      security:
      - BBOAuth2:
        - "account:manage"
  /prompts/bots:
    get:
      tags:
      - "Prompts"
      summary: "List Prompt Bots"
      description: "Returns a list of all Prompt Bots for the user."
      operationId: "GetPromptBots"
      security:
      - BBOAuth2:
        - "email:manage"
    post:
      tags:
      - "Prompts"
      summary: "Create a running Prompt Bot for a list"
      description: "Creates a Prompt Bot that sends emails to contacts on a list over\
        \ the span of time defined."
      operationId: "CreatePromptBot"
      security:
      - BBOAuth2:
        - "email:manage"
  /prompts/bots/{id}:
    put:
      tags:
      - "Prompts"
      summary: "Update Prompt Bot"
      description: "Updates a Prompt Bot's settings."
      operationId: "UpdatePromptBot"
      security:
      - BBOAuth2:
        - "email:manage"
  /prompts/campaigns/sync:
    post:
      tags:
      - "Prompts"
      summary: "Syncs Campaigns and One to Ones Subscriptions for User"
      description: "Syncs Campaigns and One to Ones Subscriptions for User based on\
        \ their profile information. The user must be a Prompt Subscriber."
      operationId: "SyncPromptSubscriptions"
      security:
      - BBOAuth2:
        - "account:manage"
  /prompts/campaigns/{clientGroupId}:
    put:
      tags:
      - "Prompts"
      summary: "Update Prompt Campaign"
      description: "Updates a Prompt Campaign's Settings"
      operationId: "UpdatePromptCampaign"
      security:
      - BBOAuth2:
        - "email:manage"
  /prompts/{id}:
    put:
      tags:
      - "Prompts"
      summary: "Update Prompt"
      description: "Updates a Prompt"
      operationId: "UpdatePrompt"
      security:
      - BBOAuth2:
        - "email:manage"
  /prompts/{id}/content:
    put:
      tags:
      - "Prompts"
      summary: "Update Prompt Content"
      description: "Updates a Prompt Content"
      operationId: "UpdatePromptTemplate"
      security:
      - BBOAuth2:
        - "email:manage"
  /prompts/{userId}/campaigns:
    get:
      tags:
      - "Prompts"
      summary: "List Prompt Campaigns"
      description: "Returns a list of all Prompt Campaigns for the user."
      operationId: "GetPromptCampaigns"
      security:
      - BBOAuth2:
        - "email:manage"
  /socials/authorizations:
    get:
      tags:
      - "Socials"
      summary: "Get authorizations for all social integration"
      description: "Get authorizations and autoshares for all social integration and\
        \ has redirect for user to login"
      operationId: "GetSocialAuthorizations"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/client/sendMechanism:
    put:
      tags:
      - "Socials"
      summary: "Gets the auto shares from the client group assoc id"
      description: "Gets the auto shares from the client group assoc id"
      operationId: "UpdateClientGroupSendMechanism"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/client/sendMechanisms:
    put:
      tags:
      - "Socials"
      summary: "Toggles the prompt campaigns in a users account"
      description: "Toggles the prompt campaigns in a users account for a social integrations\
        \ on or off"
      operationId: "UpdateClientGroupsSendMechanism"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/content:
    post:
      tags:
      - "Socials"
      summary: "Creates social content"
      description: "Creates social content for an email"
      operationId: "PostSocialContent"
      security:
      - BBOAuth2:
        - "settings:manage"
    put:
      tags:
      - "Socials"
      summary: "Updates social content"
      description: "Updates social content for an email"
      operationId: "UpdateSocialContent"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/facebook/pages:
    get:
      tags:
      - "Socials"
      summary: "Gets facebook pages"
      description: "Gets facebook pages by client id"
      operationId: "GetFacebookPages"
      security:
      - BBOAuth2:
        - "settings:manage"
    put:
      tags:
      - "Socials"
      summary: "Updates facebook page Ids"
      description: "Updates facebook page Ids to be sent to for prompts"
      operationId: "UpdateFacebookPages"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/profile:
    get:
      tags:
      - "Socials"
      summary: "Gets the profile properties"
      description: "Gets the social profile properties"
      operationId: "GetSocialProfileProperties"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/properties:
    get:
      tags:
      - "Socials"
      summary: "Gets the social email properties"
      description: "Gets the social email properties"
      operationId: "GetSocialArticleProperties"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/send:
    post:
      tags:
      - "Socials"
      summary: "Sends social content"
      description: "Sends social content for a user via their associated prompt"
      operationId: "SendSocial"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/send/retry:
    post:
      tags:
      - "Socials"
      summary: "Sends social content"
      description: "Sends social content that failed for a user via their associated\
        \ prompt"
      operationId: "RetrySocialSend"
      security:
      - BBOAuth2:
        - "settings:manage"
  /socials/{promptId}/stats:
    get:
      tags:
      - "Socials"
      summary: "Get social stats for a prompt"
      description: "Get social stats for a prompt by id"
      operationId: "GetSocialStats"
      security:
      - BBOAuth2:
        - "account:read"
  /spec:
    get:
      tags:
      - "Utilities"
      summary: "Describes this api"
      description: "Describes methods available through the API."
      operationId: "GetSpec"
      security: []
  /team/assets/:
    get:
      tags:
      - "Teams"
      summary: "Lists team assets"
      description: "Returns a collection of assets"
      operationId: "GetClientGroupAssets"
      security:
      - BBOAuth2:
        - "team:read"
  /team/associations/:
    get:
      tags:
      - "Teams"
      summary: "Lists team associations"
      description: "Returns a collection of team associations for a given user"
      operationId: "GetAllClientGroupAssociations"
      security:
      - BBOAuth2:
        - "team:read"
  /team/promptOverview:
    get:
      tags:
      - "Teams"
      summary: "Get Prompt Overview"
      description: "Get Prompt Overview"
      operationId: "GetPromptOverview"
      security:
      - BBOAuth2:
        - "team:read"
  /team/{clientGroupId}/campaign:
    get:
      tags:
      - "Teams"
      summary: "Get campaigns for team"
      description: "Get campaigns for the team and their stats"
      operationId: "GetTeamPromptCampaigns"
      security:
      - BBOAuth2:
        - "team:read"
  /team/{clientGroupId}/campaign/stats:
    get:
      tags:
      - "Teams"
      summary: "Get aggregate stats for campaigns"
      description: "Get all the campaigns aggregate stats"
      operationId: "GetTeamPromptAggregateStats"
      security:
      - BBOAuth2:
        - "team:read"
  /team/{month}/{year}/monthStats:
    get:
      tags:
      - "Teams"
      summary: "Jericho Monthly Stats"
      description: "Jericho Monthly Stats"
      operationId: "GetPromptMonthlyStats"
      security:
      - BBOAuth2:
        - "team:read"
  /team/{teamId}:
    post:
      tags:
      - "Teams"
      summary: "Update a team"
      description: "Update fields on a team"
      operationId: "UpdateTeam"
      security:
      - BBOAuth2:
        - "team:manage"
  /team/{teamId}/jericho:
    get:
      tags:
      - "Teams"
      summary: "List Jericho Sends"
      description: "Lists Jericho sends, both pending and sent."
      operationId: "GetJerichoSends"
      security:
      - BBOAuth2:
        - "team:read"
    post:
      tags:
      - "Teams"
      summary: "Creates a Jericho send."
      description: "Sends email content on behalf of members of a client group. There\
        \ are two forms this send can take:\n        Static Email, and Video Prompt.\
        \ Static emails require only an emailId.\n        Video Prompts build emails\
        \ dynamically and require most of the other fields.\n        You must be an\
        \ administrator of a Team Account to use this method."
      operationId: "QueueJerichoSend"
      security:
      - BBOAuth2:
        - "automation:manage"
  /team/{teamId}/jericho/{jerichoId}:
    put:
      tags:
      - "Teams"
      summary: "Updates the Jericho Prompt Settings"
      description: "Updates the prompt settings based on the original email id"
      operationId: "UpdateJerichoPromptSend"
      security:
      - BBOAuth2:
        - "team:manage"
    delete:
      tags:
      - "Teams"
      summary: "Cancel a Jericho Send"
      description: "Cancels a scheduled Jericho send from being sent."
      operationId: "CancelJerichoSend"
      security:
      - BBOAuth2:
        - "team:manage"
  /team/{teamId}/jericho/{jerichoId}/performance:
    get:
      tags:
      - "Teams"
      summary: "Gets Jericho performance statistics"
      description: "Returns an aggregate view of the performance of a Jericho send"
      operationId: "GetJerichoStats"
      security:
      - BBOAuth2:
        - "team:read"
  /team/{teamId}/member:
    post:
      tags:
      - "Teams"
      summary: "Add Member to Team"
      description: "Adds a member to a team."
      operationId: "AddTeamMember"
      security:
      - BBOAuth2:
        - "team:manage"
    put:
      tags:
      - "Teams"
      summary: "Update Member of Team"
      description: "Updates a member of a team"
      operationId: "UpdateTeamMember"
      security:
      - BBOAuth2:
        - "team:manage"
  /team/{teamId}/member/{userId}:
    delete:
      tags:
      - "Teams"
      summary: "Remove Member from Team"
      description: "Removes a member from a team."
      operationId: "RemoveMemberFromTeam"
      security:
      - BBOAuth2:
        - "team:manage"
  /team/{teamId}/members:
    get:
      tags:
      - "Teams"
      summary: "List Team Members"
      description: "Get a paginated listing of Team members"
      operationId: "GetPagedClientGroupMembers"
      security:
      - BBOAuth2:
        - "team:read"
    post:
      tags:
      - "Teams"
      summary: "Add users to group."
      description: "Add a new or existing user to group."
      operationId: "AddUsers"
      security:
      - BBOAuth2:
        - "team:manage"
  /team/{teamId}/members/csv:
    post:
      tags:
      - "Teams"
      summary: "Add members to group from CSV"
      description: "Imports members to a group from a given CSV ID."
      operationId: "AddUsersFromCsv"
      security:
      - BBOAuth2:
        - "team:manage"
  /team/{teamId}/stats:
    get:
      tags:
      - "Teams"
      summary: "Get Team statistics"
      description: "Get top level statistic data for a Team"
      operationId: "GetClientGroupStatistics"
      security:
      - BBOAuth2:
        - "team:read"
  /team/{teamId}/subteam:
    get:
      tags:
      - "Teams"
      summary: "List Subteams"
      description: "Returns a collection of subteams for a parent team"
      operationId: "GetSubteams"
      security: []
    post:
      tags:
      - "Teams"
      summary: "Add a Subteam"
      description: "Adds a subteam to a parent team"
      operationId: "CreateSubteam"
      security:
      - BBOAuth2:
        - "team:manage"
    delete:
      tags:
      - "Teams"
      summary: "Delete Subteam"
      description: "Deletes a subteam"
      operationId: "DeleteSubteam"
      security:
      - BBOAuth2:
        - "team:manage"
  /team/{teamId}/{memberUserId}/rewelcome:
    post:
      tags:
      - "Teams"
      summary: "Resend invite"
      description: "Resend invitation to a member of a team"
      operationId: "ResendTeamMemberInvitation"
      security:
      - BBOAuth2:
        - "team:manage"
  /teams/prompt/invite:
    post:
      tags:
      - "Teams"
      summary: "Invite a list to join the admin's social prompt team"
      description: "Invite to Social Prompt Team"
      operationId: "InviteToSocialPromptTeam"
      security:
      - BBOAuth2:
        - "team:manage"
  /users/profile/information:
    get:
      tags:
      - "Users"
      summary: "Get user profile information."
      description: "Get the users profile information."
      operationId: "GetUserProfileInfo"
      security:
      - BBOAuth2:
        - "account:read"
  /video/signedUpload:
    post:
      tags:
      - "Videos"
      summary: "Generate Signed Url"
      description: "Generates a signed url to be used for video uploads."
      operationId: "SignUpload"
      security: []
  /videos/live/getRecorder:
    get:
      tags:
      - "Videos"
      summary: "Get Live Video Recorder HTML"
      description: "Returns an object with a number of properties to help you put\
        \ a video recorder on your site.\n        This is to be used in conjunction\
        \ with the VideoRecordedLive call one the user has confirmed in your UI that\n\
        \        the video is how they want it."
      operationId: "GetVideoRecorder"
      security:
      - BBOAuth2:
        - "video:manage"
  /videos/live/markComplete:
    post:
      tags:
      - "Videos"
      summary: "Completes a live recording"
      description: "Used in conjunction with the live recorder method to mark a video\
        \ recording as complete."
      operationId: "MarkLiveRecordingComplete"
      security:
      - BBOAuth2:
        - "video:manage"
  /videos/thumbnail:
    put:
      tags:
      - "Videos"
      summary: "Upload thumbnail"
      description: "Upload a new video thumbnail"
      operationId: "UpdateVideoThumbnailV2"
      security:
      - BBOAuth2:
        - "video:manage"
  /videos/{videoId}/status:
    get:
      tags:
      - "Videos"
      summary: "Video Encoding Status"
      description: "Get information about the current state of encoding for a given\
        \ video id."
      operationId: "GetVideoEncodingStatus"
      security:
      - BBOAuth2:
        - "video:read"
  /webhook:
    post:
      tags:
      - "Webhooks"
      summary: "Add Webhook"
      description: "Idempotently adds a Webhook url"
      operationId: "AddWebHook"
      security:
      - BBOAuth2:
        - "all:manage"
  /webhook/:
    get:
      tags:
      - "Webhooks"
      summary: "Lists Webhooks"
      description: "Lists all registered Webhooks"
      operationId: "GetWebHooks"
      security:
      - BBOAuth2:
        - "all:manage"
  /webhook/events:
    get:
      tags:
      - "Webhooks"
      summary: "Describe WebHook Events"
      description: "Returns example Webhook events for each kind of possible event."
      operationId: "ListWebHookEvents"
      security: []
  /webhook/test:
    post:
      tags:
      - "Webhooks"
      summary: "Sends test Webhook"
      description: "Triggers a test webhook to be sent to your endpoints."
      operationId: "SendWebhookExample"
      security:
      - BBOAuth2:
        - "all:manage"
  /webhook/{hookId}:
    delete:
      tags:
      - "Webhooks"
      summary: "Deletes Webhook"
      description: "Deletes a Webhook"
      operationId: "DeleteWebHook"
      security:
      - BBOAuth2:
        - "all:manage"
securityDefinitions:
  BBOAuth2:
    type: "oauth2"
    authorizationUrl: "https://app.bombbomb.com/auth/authorize"
    flow: "implicit"
    scopes:
      all:manage: "View & Manage your BombBomb information"
      all:read: "View your BombBomb information"
      email:manage: "View & Manage your BombBomb emails"
      email:read: "View your BombBomb emails"
      video:manage: "View & Manage your BombBomb videos"
      video:read: "View your BombBomb videos"
      contact:manage: "View & Manage your BombBomb contacts"
      contact:read: "View your BombBomb contacts"
      curriculum:manage: "View & Manage your BombBomb challenges"
      curriculum:read: "View your BombBomb challenges"
      automation:manage: "View & Manage your BombBomb automations"
      automation:read: "View your BombBomb automations"
      form:manage: "View & Manage your BombBomb forms"
      form:read: "View your BombBomb forms"
      list:manage: "View & Manage your BombBomb lists"
      team:manage: "View & Manage your BombBomb teams"
      team:read: "View your BombBomb teams"
      order:manage: "Manage your BombBomb orders"
      settings:manage: "Manage your BombBomb settings"
      file:manage: "View & Manage your BombBomb files"
      file:read: "View your BombBomb files"
      account:manage: "View & Manage your BombBomb account"
      account:read: "View your BombBomb account"